language: python
python: 3.7
dist: bionic
services:
  - docker
env:
- WHEELHOUSE=$HOME/.cache/wheelhouse PIP_FIND_LINKS=file://$WHEELHOUSE PIP_WHEEL_DIR=$WHEELHOUSE
cache:
  directories:
  - "$HOME/.cache/pip"
  - "$HOME/.cache/wheelhouse"
  - portiaui/node_modules
  - portiaui/bower_components

before_install:
  - docker build -t scrapinghub/portia .
  - docker ps -a

install:
- docker run scrapinghub/portia /app/docker/run-tests.sh
- pushd portiaui
- nvm install 10.16.0
- nvm use 10.16.0
- npm install -g bower ember-cli@2.6.3
- npm install
- bower install
- popd

script:
- pushd portiaui
- npm rebuild node-sass
- npm test
- popd

before_deploy:
- cd slybot
- pip install twine
- sudo chown -R $USER .
deploy:
  provider: pypi
  distributions: sdist bdist_wheel
  user: scrapinghub
  password:
    secure: S5hZT2YBncUSkPTyR5RUQnACfTsW2ZtpHeQucIamKWN+xkE8KK9O0cWUMuKQ0q3U5ShFkZdhO4PnBjvtP54Dq9IogJAudkDJCylctf4qGoIlWu01mAoJzcUfrS5KW+VolF/opBJObwG38EIOOsVy9UYq7DeQcryAAG1RuMjONAk=
  on:
    all_branches: true
    tags: true
    repo: scrapinghub/portia
    condition: "$TRAVIS_TAG =~ ^slybot-[0-9][.][0-9]*"
